### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Aonysen** [dzxrly/BF2042State#3]
大佬大佬，可以在首页添加一个栏位，固定显示几个常搜的id及其平台嘛？每一次都要手动输id再选平台确实有点麻烦。在这里先谢谢大佬了( ˝ᗢ̈˝ )

**Comment by dzxrly** [comment]
1.1.1版本是有查询历史记录的，但是没有保存平台信息，预计下一次更新会把`查询ID+游戏平台`一起保存。

**Comment by dzxrly** [comment]
感谢反馈，最新版1.1.2已添加同时保存玩家昵称与游戏平台的功能，[Release Ver.1.1.2](https://github.com/dzxrly/BF2042State/releases/tag/1.1.2)

**Comment by Aonysen** [comment]
感谢！大佬太强了⸜₍๑•⌔•๑₎⸝
